### ISSUE TITLE
Add phpredis module

### ISSUE THREAD

**Issue by ipf** [mblaschke/TYPO3-docker-boilerplate#102]
When using redis with php the [predis](https://github.com/nrk/predis) library is needed, but missing in the boilderplate

**Comment by wt69** [comment]
+1
Anyone an idea how to do this? Need redis support urgently :(

**Comment by mblaschke** [comment]
Because I'm currently not using redis: What do you need? Isn't it something you can fetch via `composer`?

**Comment by wt69** [comment]
Hi Markus,

I need the redis extension for PHP because I use redis as cache backend.

This ist the extension I use for my local installation:
https://github.com/phpredis/phpredis

This ist the failure message from the frontend:
The PHP extension "redis" must be installed and loaded in order to use the redis backend.

Any Idea how to implent this?

Thank you
Thomas

**Comment by mblaschke** [comment]
Is this the same extension as http://packages.ubuntu.com/search?keywords=php5-redis&searchon=names&suite=wily&section=all ? Then i can add this to all debian/ubuntu images

**Comment by wt69** [comment]
I think this extension should work. It would be great if you ca do this.

**Comment by mblaschke** [comment]
Workaround until redis is availabe, add to your Dockerfile:
`RUN /usr/local/bin/apt-install php5-redis`

**Comment by mblaschke** [comment]
For faster communication join us at slack: https://webdevops.io/slack/
