### ISSUE TITLE
Store MySQL data in /storage

### ISSUE THREAD

**Issue by stucki** [mblaschke/TYPO3-docker-boilerplate#172]
Similar to Solr, the MySQL database should be stored below in the `storage` container.

Suggestions:
a) Move MySQL data dir from `/var/lib/mysql` to `/storage/mysql`
b) Add `/var/lib/mysql` to the volumes of the `storage` container

In both cases, additional changes will be necessary because the folder is empty at start.
Possible solution: Copy the contents of `/var/lib/mysql` to `/storage/mysql` if the folder is empty.

**Comment by mblaschke** [comment]
Maybe we should get rid of the storage container because we don't need it anymore?
Currently every container stores the data inside as volume which seems to be fine and fast.

Storing the data in a volume inside `storage` container would also be an option so the data isn't lost if the containers are removed. But this requires additional configuration.

Or we can configure this inside `docker-compose.yml` and can also remove `storage`.

**Comment by stucki** [comment]
Yes it's all about persistence when replacing a container. I used to store /var/lib/mysql on the host, but still think it should go into a volume or a container...

**Comment by mblaschke** [comment]
Implemented with dea6208cedc4774e9cfdb115fbd14d6086784b07
