### ISSUE TITLE
TYPO3 creates files as root on the OS X level

### ISSUE THREAD

**Issue by elmar-hinz** [mblaschke/TYPO3-docker-boilerplate#84]
Software nesting: `OS X -> Virtualbox -> vagrant-development -> docker -> docker container -> TYPO3`

It's a wonder that the docker container can be mounted onto `./code/` on OS X at all. Now when TYPO3/PHP creates files or directories, they are created as `root` on OS X. To remove them I need to call `sudo`.

In the ideal world they would be created as my OS X user.

**Comment by mblaschke** [comment]
It's an issue of the vagrant box not of the boilerplate.
Hopefully the next vagrant box commits will fix this issue.

But the container is running with UID 1000 (default) so files should not be created as root.. strage

**Comment by elmar-hinz** [comment]
Very strange! I start a process and the process writes files with root privileges? Can't be true.

Can't? Well I opened one door: [ENABLING NFS SYNCED FOLDERS](https://docs.vagrantup.com/v2/synced-folders/nfs.html) for the vagrant startup.

_/etc/sudoers_:

```
%sudo ALL=(root) NOPASSWD: VAGRANT_EXPORTS_ADD, VAGRANT_NFSD_CHECK, VAGRANT_NFSD_START, VAGRANT_NFSD_APPLY, VAGRANT_EXPORTS_REMOVE
```

Something in this approach looks fatal to me. Does it explain this strangeness?

**Comment by mblaschke** [comment]
The sudoers entry only allows Vagrant to add/remove entries into `/etc/exports` for NFS shares.

The Vagrant VM is using a file share with an exported NFS share to read and write files from the host. Normally if root (uid=0) is creating files the original file is created as root (uid=0). Maybe it's fixed with latest version of Vagrant VM.
Please check again.

BTW: php-fpm is running as www-data (uid=1000) as default so all files should have at least uid 1000 if files are created by php.

**Comment by elmar-hinz** [comment]
This is fixed meanwhile.
